#!/usr/bin/env bash
# infra/caddy-add-domain.sh
# -------------------------
# Add a custom domain to PremDev so Caddy gets a wildcard SSL cert for it
# and routes workspace subdomains on that domain to the app.
#
# Usage:
#   sudo bash infra/caddy-add-domain.sh netprem.org
#
# What it does:
#   1. Creates /opt/premdev/data/caddy/<domain>.caddy  (Caddy snippet)
#   2. Creates /opt/premdev/data/caddy/ dir if missing
#   3. Reloads Caddy (picks up the new snippet + requests wildcard cert)
#
# Pre-requisites:
#   - Cloudflare wildcard A record   *.netprem.org → VPS IP  (DNS only, not proxied)
#   - Domain registered in PremDev Admin panel  (Admin → Domains → Add)
#   - /opt/premdev/.env  must have CF_API_TOKEN with Zone:DNS:Edit for this domain

set -euo pipefail

DOMAIN="${1:-}"
if [[ -z "$DOMAIN" ]]; then
  echo "Usage: sudo bash $0 <domain>"
  echo "Example: sudo bash $0 netprem.org"
  exit 1
fi

# Sanitise: lowercase, strip leading/trailing dots/spaces
DOMAIN="$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]' | sed 's/^[. ]*//;s/[. ]*$//')"

CADDY_EXTRA_DIR="/opt/premdev/data/caddy/extra"
SNIPPET="$CADDY_EXTRA_DIR/$DOMAIN.caddy"
COMPOSE_FILE="${COMPOSE_FILE:-/opt/premdev/docker-compose.yml}"
ENV_FILE="${ENV_FILE:-/opt/premdev/.env}"

[[ -f "$COMPOSE_FILE" ]] || {
  echo "❌  Compose file not found: $COMPOSE_FILE"
  exit 1
}

# Load CF_API_TOKEN from .env so we can embed it in the snippet
if [[ -f /opt/premdev/.env ]]; then
  # shellcheck disable=SC1091
  set +o nounset
  source <(grep -E '^(CF_API_TOKEN)=' /opt/premdev/.env | sed "s/^/export /")
  set -o nounset
fi

CF_TOKEN="${CF_API_TOKEN:-}"
if [[ -z "$CF_TOKEN" ]]; then
  echo "❌  CF_API_TOKEN not found in /opt/premdev/.env"
  echo "    Add it first:  sudo nano /opt/premdev/.env"
  exit 1
fi

mkdir -p "$CADDY_EXTRA_DIR"

echo "→ Writing Caddy snippet: $SNIPPET"
cat > "$SNIPPET" <<CADDY
# Auto-generated by infra/caddy-add-domain.sh for $DOMAIN
# To remove: delete this file then run: docker compose -f $COMPOSE_FILE exec caddy caddy reload --config /etc/caddy/Caddyfile
*.${DOMAIN}, ${DOMAIN} {
        tls {
                dns cloudflare ${CF_TOKEN}
        }

        # Apex domain → same landing page as primary domain
        @apex_${DOMAIN//./_} host ${DOMAIN}
        handle @apex_${DOMAIN//./_} {
                root * /srv/landing
                try_files {path} /index.html
                file_server
        }

        # Any subdomain on this domain → workspace proxy (same as PRIMARY_DOMAIN)
        @ws_${DOMAIN//./_} header_regexp ws_${DOMAIN//./_} Host ^[a-z0-9](?:[a-z0-9-]{0,48}[a-z0-9])?\.${DOMAIN}$
        handle @ws_${DOMAIN//./_} {
                reverse_proxy app:3001 {
                        transport http {
                                dial_timeout 5s
                                response_header_timeout 120s
                        }
                        header_up Host {host}
                        header_up X-Real-IP {remote}
                        header_up X-Forwarded-Proto https
                }
        }

        handle {
                respond "Unknown subdomain" 404
        }
}
CADDY

echo "→ Reloading Caddy..."
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" \
  exec -T caddy caddy reload --config /etc/caddy/Caddyfile

echo ""
echo "✅  Done! Caddy will now request a wildcard cert for *.${DOMAIN}"
echo ""
echo "Next steps:"
echo "  1. Make sure you have a Cloudflare DNS record:"
echo "       *   A   <VPS_IP>   DNS only (not proxied)"
echo "     for domain: ${DOMAIN}"
echo "  2. In PremDev Admin panel → Domains → verify ${DOMAIN} is Active"
echo "  3. Wait ~30 seconds for Caddy to finish getting the cert"
echo "  4. Test: open https://app.${DOMAIN} — should redirect to IDE or show landing"
