/**
 * caddy.ts — helpers to auto-generate per-domain Caddy config snippets
 * and reload Caddy whenever the admin adds / removes a custom domain.
 *
 * Snippet files live at:
 *   HOST:  /opt/premdev/data/caddy/extra/<domain>.caddy
 *   APP:   {DATA_DIR}/caddy/extra/<domain>.caddy   (same dir, different view)
 *
 * The Caddyfile must contain:  import /etc/caddy/extra/*.caddy
 * The docker-compose must mount:
 *   - /opt/premdev/data/caddy/extra:/etc/caddy/extra:ro  (for Caddy container)
 *   - /opt/premdev/data/caddy/extra → accessible via DATA_DIR/caddy/extra in app
 */

import fs from "node:fs";
import path from "node:path";
import { config } from "./config.js";
import { getActiveDomains } from "./db.js";
import { docker } from "./runtime.js";

const EXTRA_DIR = path.join(config.DATA_DIR, "caddy", "extra");
function cloudflareToken(): string {
  return process.env.CF_API_TOKEN ?? "";
}

function domainSnippet(domain: string, cfToken: string): string {
  const safeName = domain.replace(/\./g, "_");
  return `# Auto-generated by PremDev Admin — do not edit manually
# To remove: delete this file via Admin > Domains, then Caddy reloads automatically
*.${domain}, ${domain} {
        tls {
                dns cloudflare ${cfToken}
        }

        @apex_${safeName} host ${domain}
        handle @apex_${safeName} {
                root * /srv/landing
                try_files {path} /index.html
                file_server
        }

        @code_${safeName} host code-*.${domain}
        handle @code_${safeName} {
                reverse_proxy app:3001 {
                        transport http {
                                dial_timeout 10s
                                read_timeout 24h
                                write_timeout 24h
                        }
                        flush_interval -1
                        header_up Host {host}
                        header_up X-Real-IP {remote}
                        header_up X-Forwarded-Proto https
                }
        }

        @ws_${safeName} header_regexp ws_${safeName} Host ^[a-z0-9](?:[a-z0-9_-]{0,48}[a-z0-9])?\\.${domain.replace(/\./g, "\\.")}(?::[0-9]+)?$
        handle @ws_${safeName} {
                reverse_proxy app:3001 {
                        transport http {
                                dial_timeout 5s
                                response_header_timeout 120s
                        }
                        header_up Host {host}
                        header_up X-Real-IP {remote}
                        header_up X-Forwarded-Proto https
                }
        }

        handle {
                respond "Unknown subdomain" 404
        }
}
`;
}

/** Write a snippet file for the given domain. No-op in dev (no CF token). */
export function writeDomainSnippet(domain: string): void {
  const cfToken = cloudflareToken();
  if (!cfToken) {
    console.warn(`[caddy] Cannot write snippet for ${domain}: CF_API_TOKEN is not configured`);
    return;
  }
  try {
    fs.mkdirSync(EXTRA_DIR, { recursive: true });
    fs.writeFileSync(path.join(EXTRA_DIR, `${domain}.caddy`), domainSnippet(domain, cfToken), "utf8");
  } catch (e) {
    console.warn(`[caddy] Failed to write snippet for ${domain}:`, e);
  }
}

/**
 * Rebuild snippets for domains that are already active in SQLite.
 *
 * The domain registry and the Caddy snippets are separate persistence
 * surfaces. A redeploy can preserve the registry while losing the generated
 * files, so the API must reconcile them on every startup.
 */
export function syncActiveDomainSnippets(): number {
  const domains = getActiveDomains();
  const active = new Set(domains.map((domain) => `${domain}.caddy`));
  try {
    fs.mkdirSync(EXTRA_DIR, { recursive: true });
    for (const file of fs.readdirSync(EXTRA_DIR)) {
      if (file.endsWith(".caddy") && !active.has(file)) {
        fs.unlinkSync(path.join(EXTRA_DIR, file));
      }
    }
  } catch (e) {
    console.warn("[caddy] Failed to reconcile custom-domain snippets:", e);
  }
  for (const domain of domains) writeDomainSnippet(domain);
  return domains.length;
}

/** Delete the snippet file for the given domain. */
export function deleteDomainSnippet(domain: string): void {
  try {
    const f = path.join(EXTRA_DIR, `${domain}.caddy`);
    if (fs.existsSync(f)) fs.unlinkSync(f);
  } catch (e) {
    console.warn(`[caddy] Failed to delete snippet for ${domain}:`, e);
  }
}

/**
 * Find the running Caddy container and exec `caddy reload` inside it.
 * Silently swallowed on any error so domain DB operations always succeed.
 */
export async function reloadCaddy(): Promise<void> {
  if (!docker) return;
  try {
    const containers = await docker.listContainers();
    const caddyCt = containers.find((c) =>
      c.Names.some((n) => n.toLowerCase().includes("caddy")),
    );
    if (!caddyCt) {
      console.warn("[caddy] Caddy container not found — skipping reload");
      return;
    }
    const ct = docker.getContainer(caddyCt.Id);
    const exec = await ct.exec({
      Cmd: ["caddy", "reload", "--config", "/etc/caddy/Caddyfile", "--force"],
      AttachStdout: true,
      AttachStderr: true,
    });
    await exec.start({});
    console.log(`[caddy] Reloaded (container: ${caddyCt.Names[0]})`);
  } catch (e) {
    console.warn("[caddy] reload failed (non-fatal):", e);
  }
}
